$(document).ready(function () {
    console.log("i work");
getData();

    
});

function getData(){
    console.log("does this work");
    $.getJSON('/web_project/js/item_data.json', function (data) {
      console.log(data);
        
        var name0 = data[0].name;
        var name1 = data[1].name;        
        var name2 = data[2].name;
        var name3 = data[3].name;
        var name4 = data[4].name;
        var name5 = data[5].name;
        var name6 = data[6].name;
        var name7 = data[7].name;
        var name8 = data[8].name;
        var name9 = data[9].name;
        var name10 = data[10].name;
        var name11 = data[11].name;        
        var name12 = data[12].name;
        var name13 = data[13].name;
        var name14 = data[14].name;
        var name15 = data[15].name;
        var name16 = data[16].name;
        var name17 = data[17].name;
        var name18 = data[18].name;
        var name19 = data[19].name;
        var name20 = data[20].name;
        var name21 = data[21].name;
        var name22 = data[22].name;
        var name23 = data[23].name;
        var name24 = data[24].name;
        var name25 = data[25].name;
        var name26 = data[26].name;
        var name27 = data[27].name;
        var name28 = data[28].name;
        var name29 = data[29].name;
        
        var price0 = data[0].price;
        var price1 = data[1].price;        
        var price2 = data[2].price;
        var price3 = data[3].price;
        var price4 = data[4].price;
        var price5 = data[5].price;
        var price6 = data[6].price;
        var price7 = data[7].price;
        var price8 = data[8].price;
        var price9 = data[9].price;
        var price10 = data[10].price;
        var price11 = data[11].price;        
        var price12 = data[12].price;
        var price13 = data[13].price;
        var price14 = data[14].price;
        var price15 = data[15].price;
        var price16 = data[16].price;
        var price17 = data[17].price;
        var price18 = data[18].price;
        var price19 = data[19].price;
        var price20 = data[20].price;
        var price21 = data[21].price;
        var price22 = data[22].price;
        var price23 = data[23].price;
        var price24 = data[24].price;
        var price25 = data[25].price;
        var price26 = data[26].price;
        var price27 = data[27].price;
        var price28 = data[28].price;
        var price29 = data[29].price;
        
        var size0 = data[0].size;
        var size1 = data[1].size;        
        var size2 = data[2].size;
        var size3 = data[3].size;
        var size4 = data[4].size;
        var size5 = data[5].size;
        var size6 = data[6].size;
        var size7 = data[7].size;
        var size8 = data[8].size;
        var size9 = data[9].size;
        var size10 = data[10].size;
        var size11 = data[11].size;        
        var size12 = data[12].size;
        var size13 = data[13].size;
        var size14 = data[14].size;
        var size15 = data[15].size;
        var size16 = data[16].size;
        var size17 = data[17].size;
        var size18 = data[18].size;
        var size19 = data[19].size;
        var size20 = data[20].size;
        var size21 = data[21].size;
        var size22 = data[22].size;
        var size23 = data[23].size;
        var size24 = data[24].size;
        var size25 = data[25].size;
        var size26 = data[26].size;
        var size27 = data[27].size;
        var size28 = data[28].size;
        var size29 = data[29].size;
                
        var picture0 = data[0].picture;
        var picture1 = data[1].picture;        
        var picture2 = data[2].picture;
        var picture3 = data[3].picture;
        var picture4 = data[4].picture;
        var picture5 = data[5].picture;
        var picture6 = data[6].picture;
        var picture7 = data[7].picture;
        var picture8 = data[8].picture;
        var picture9 = data[9].picture;
        var picture10 = data[10].picture;
        var picture11 = data[11].picture;        
        var picture12 = data[12].picture;
        var picture13 = data[13].picture;
        var picture14 = data[14].picture;
        var picture15 = data[15].picture;
        var picture16 = data[16].picture;
        var picture17 = data[17].picture;
        var picture18 = data[18].picture;
        var picture19 = data[19].picture;
        var picture20 = data[20].picture;
        var picture21 = data[21].picture;
        var picture22 = data[22].picture;
        var picture23 = data[23].picture;
        var picture24 = data[24].picture;
        var picture25 = data[25].picture;
        var picture26 = data[26].picture;
        var picture27 = data[27].picture;
        var picture28 = data[28].picture;
        var picture29 = data[29].picture;
                
        var discription0 = data[0].discription;
        var discription1 = data[1].discription;        
        var discription2 = data[2].discription;
        var discription3 = data[3].discription;
        var discription4 = data[4].discription;
        var discription5 = data[5].discription;
        var discription6 = data[6].discription;
        var discription7 = data[7].discription;
        var discription8 = data[8].discription;
        var discription9 = data[9].discription;
        var discription10 = data[10].discription;
        var discription11 = data[11].discription;        
        var discription12 = data[12].discription;
        var discription13 = data[13].discription;
        var discription14 = data[14].discription;
        var discription15 = data[15].discription;
        var discription16 = data[16].discription;
        var discription17 = data[17].discription;
        var discription18 = data[18].discription;
        var discription19 = data[19].discription;
        var discription20 = data[20].discription;
        var discription21 = data[21].discription;
        var discription22 = data[22].discription;
        var discription23 = data[23].discription;
        var discription24 = data[24].discription;
        var discription25 = data[25].discription;
        var discription26 = data[26].discription;
        var discription27 = data[27].discription;
        var discription28 = data[28].discription;
        var discription29 = data[29].discription;
        
        $("#name0").html(name0);
        $("#name1").html(name1);
        $("#name2").html(name2);
        $("#name3").html(name3);
        $("#name4").html(name4);
        $("#name5").html(name5);
        $("#name6").html(name6);
        $("#name7").html(name7);
        $("#name8").html(name8);
        $("#name9").html(name9);
        $("#name10").html(name10);
        $("#name11").html(name11);
        $("#name12").html(name12);
        $("#name13").html(name13);
        $("#name14").html(name14);
        $("#name15").html(name15);
        $("#name16").html(name16);
        $("#name17").html(name17);
        $("#name18").html(name18);
        $("#name19").html(name19);
        $("#name20").html(name20);
        $("#name21").html(name21);
        $("#name22").html(name22);
        $("#name23").html(name23);
        $("#name24").html(name24);
        $("#name25").html(name25);
        $("#name26").html(name26);
        $("#name27").html(name27);
        $("#name28").html(name28);
        $("#name29").html(name29);
        
        $("#price0").html(price0);
        $("#price1").html(price1);
        $("#price2").html(price2);
        $("#price3").html(price3);
        $("#price4").html(price4);
        $("#price5").html(price5);
        $("#price6").html(price6);
        $("#price7").html(price7);
        $("#price8").html(price8);
        $("#price9").html(price9);
        $("#price10").html(price10);
        $("#price11").html(price11);
        $("#price12").html(price12);
        $("#price13").html(price13);
        $("#price14").html(price14);
        $("#price15").html(price15);
        $("#price16").html(price16);
        $("#price17").html(price17);
        $("#price18").html(price18);
        $("#price19").html(price19);
        $("#price20").html(price20);
        $("#price21").html(price21);
        $("#price22").html(price22);
        $("#price23").html(price23);
        $("#price24").html(price24);
        $("#price25").html(price25);
        $("#price26").html(price26);
        $("#price27").html(price27);
        $("#price28").html(price28);
        $("#price29").html(price29);
        
        $("#size0").html(size0);
        $("#size1").html(size1);
        $("#size2").html(size2);
        $("#size3").html(size3);
        $("#size4").html(size4);
        $("#size5").html(size5);
        $("#size6").html(size6);
        $("#size7").html(size7);
        $("#size8").html(size8);
        $("#size9").html(size9);
        $("#size10").html(size10);
        $("#size11").html(size11);
        $("#size12").html(size12);
        $("#size13").html(size13);
        $("#size14").html(size14);
        $("#size15").html(size15);
        $("#size16").html(size16);
        $("#size17").html(size17);
        $("#size18").html(size18);
        $("#size19").html(size19);
        $("#size20").html(size20);
        $("#size21").html(size21);
        $("#size22").html(size22);
        $("#size23").html(size23);
        $("#size24").html(size24);
        $("#size25").html(size25);
        $("#size26").html(size26);
        $("#size27").html(size27);
        $("#size28").html(size28);
        $("#size29").html(size29);
        
        $("#discription0").html(discription0);
        $("#discription1").html(discription1);
        $("#discription2").html(discription2);
        $("#discription3").html(discription3);
        $("#discription4").html(discription4);
        $("#discription5").html(discription5);
        $("#discription6").html(discription6);
        $("#discription7").html(discription7);
        $("#discription8").html(discription8);
        $("#discription9").html(discription9);
        $("#discription10").html(discription10);
        $("#discription11").html(discription11);
        $("#discription12").html(discription12);
        $("#discription13").html(discription13);
        $("#discription14").html(discription14);
        $("#discription15").html(discription15);
        $("#discription16").html(discription16);
        $("#discription17").html(discription17);
        $("#discription18").html(discription18);
        $("#discription19").html(discription19);
        $("#discription20").html(discription20);
        $("#discription21").html(discription21);
        $("#discription22").html(discription22);
        $("#discription23").html(discription23);
        $("#discription24").html(discription24);
        $("#discription25").html(discription25);
        $("#discription26").html(discription26);
        $("#discription27").html(discription27);
        $("#discription28").html(discription28);
        $("#discription29").html(discription29);
        
        $("#picture0").attr('src', picture0);
        $("#picture1").attr('src', picture1);
        $("#picture2").attr('src', picture2);
        $("#picture3").attr('src', picture3);
        $("#picture4").attr('src', picture4);
        $("#picture5").attr('src', picture5);
        $("#picture6").attr('src', picture6);
        $("#picture7").attr('src', picture7);
        $("#picture8").attr('src', picture8);
        $("#picture9").attr('src', picture9);
        $("#picture10").attr('src', picture10);
        $("#picture11").attr('src', picture11);
        $("#picture12").attr('src', picture12);
        $("#picture13").attr('src', picture13);
        $("#picture14").attr('src', picture14);
        $("#picture15").attr('src', picture15);
        $("#picture16").attr('src', picture16);
        $("#picture17").attr('src', picture17);
        $("#picture18").attr('src', picture18);
        $("#picture19").attr('src', picture19);
        $("#picture20").attr('src', picture20);
        $("#picture21").attr('src', picture21);
        $("#picture22").attr('src', picture22);
        $("#picture23").attr('src', picture23);
        $("#picture24").attr('src', picture24);
        $("#picture25").attr('src', picture25);
        $("#picture26").attr('src', picture26);
        $("#picture27").attr('src', picture27);
        $("#picture28").attr('src', picture28);
        $("#picture29").attr('src', picture29);
        
        $("#picture0").attr('alt', "image of " + name0);
        $("#picture1").attr('alt', "image of " + name1);
        $("#picture2").attr('alt', "image of " + name2);
        $("#picture3").attr('alt', "image of " + name3);
        $("#picture4").attr('alt', "image of " + name4);
        $("#picture5").attr('alt', "image of " + name5);
        $("#picture6").attr('alt', "image of " + name6);
        $("#picture7").attr('alt', "image of " + name7);
        $("#picture8").attr('alt', "image of " + name8);
        $("#picture9").attr('alt', "image of " + name9);
        $("#picture10").attr('alt', "image of " + name10);
        $("#picture11").attr('alt', "image of " + name11);
        $("#picture12").attr('alt', "image of " + name12);
        $("#picture13").attr('alt', "image of " + name13);
        $("#picture14").attr('alt', "image of " + name14);
        $("#picture15").attr('alt', "image of " + name15);
        $("#picture16").attr('alt', "image of " + name16);
        $("#picture17").attr('alt', "image of " + name17);
        $("#picture18").attr('alt', "image of " + name18);
        $("#picture19").attr('alt', "image of " + name19);
        $("#picture20").attr('alt', "image of " + name20);
        $("#picture21").attr('alt', "image of " + name21);
        $("#picture22").attr('alt', "image of " + name22);
        $("#picture23").attr('alt', "image of " + name23);
        $("#picture24").attr('alt', "image of " + name24);
        $("#picture25").attr('alt', "image of " + name25);
        $("#picture26").attr('alt', "image of " + name26);
        $("#picture27").attr('alt', "image of " + name27);
        $("#picture28").attr('alt', "image of " + name28);
        $("#picture29").attr('alt', "image of " + name29);
        
  });
}